#!/bin/sh

cd /app

echo 'Running isort'
isort .

echo 'Running autoflake'
autoflake --in-place --remove-all-unused-imports --ignore-init-module-imports --exclude venv,worker/venv --recursive .

echo 'Running autopep8'
#PYTHONPATH=backend autopep8 --in-place --recursive --global-config=./pyproject.toml --exclude=./venv --exclude=./worker/venv .
find . -name '*.py' -not -path './venv/*' -exec autopep8 --in-place --aggressive --aggressive --max-line-length 90 {} \;
