"""empty message

Revision ID: 5a626d5e701d
Revises: 
Create Date: 2024-05-31 19:53:58.280180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a626d5e701d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('tournaments',
    sa.Column('tournament_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date_beginning', sa.Date(), nullable=False),
    sa.Column('date_ending', sa.Date(), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('jtr_link', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('tournament_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_is_part_of_team',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'team_id')
    )
    op.create_table('videos',
    sa.Column('video_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=50), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('team_one_id', sa.Integer(), nullable=False),
    sa.Column('team_two_id', sa.Integer(), nullable=False),
    sa.Column('upload_date', sa.Date(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['team_one_id'], ['teams.team_id'], name='fk_videos_team_one'),
    sa.ForeignKeyConstraint(['team_two_id'], ['teams.team_id'], name='fk_videos_team_two'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.tournament_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('video_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    op.drop_table('user_is_part_of_team')
    op.drop_table('users')
    op.drop_table('tournaments')
    op.drop_table('teams')
    # ### end Alembic commands ###
