"""empty message

Revision ID: 953eccf79eda
Revises: 37cc5e23f0fd
Create Date: 2024-05-31 20:54:00.911750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953eccf79eda'
down_revision = '37cc5e23f0fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
