"""empty message

Revision ID: 9d185c531271
Revises: d4e90dd6ba44
Create Date: 2024-06-16 14:22:36.930658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d185c531271'
down_revision = 'd4e90dd6ba44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_one_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('team_two_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('videos_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'teams', ['team_two_id'], ['id'])
        batch_op.create_foreign_key(None, 'teams', ['team_one_id'], ['id'])
        batch_op.drop_column('team_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('videos_ibfk_3', 'teams', ['team_id'], ['id'])
        batch_op.drop_column('team_two_id')
        batch_op.drop_column('team_one_id')

    # ### end Alembic commands ###
