"""Update enums

Revision ID: 16de9d54ae78
Revises: aa39d007cdb9
Create Date: 2025-04-26 23:41:16.582013

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16de9d54ae78'
down_revision = 'aa39d007cdb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column(
            'category',
            existing_type=mysql.ENUM(
                'REPORTS',
                'HIGHLIGHTS',
                'SPARBUILDING',
                'MATCH',
                'SONG',
                'PODCAST',
                'AWARDS',
                'TRAINING',
                'OTHER'),
            type_=sa.Enum(
                'AWARDS',
                'HIGHLIGHTS',
                'MATCH',
                'OTHER',
                'PODCAST',
                'REPORTS',
                'SONG',
                'SPARBUILDING',
                'TRAINING',
                name='videocategoriesenum'),
            existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column(
            'category',
            existing_type=sa.Enum(
                'AWARDS',
                'HIGHLIGHTS',
                'MATCH',
                'OTHER',
                'PODCAST',
                'REPORTS',
                'SONG',
                'SPARBUILDING',
                'TRAINING',
                name='videocategoriesenum'),
            type_=mysql.ENUM(
                'REPORTS',
                'HIGHLIGHTS',
                'SPARBUILDING',
                'MATCH',
                'SONG',
                'PODCAST',
                'AWARDS',
                'TRAINING',
                'OTHER'),
            existing_nullable=False)

    # ### end Alembic commands ###
