"""Initial migration

Revision ID: aa39d007cdb9
Revises:
Create Date: 2025-04-05 22:56:28.084540

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'aa39d007cdb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'channels',
        sa.Column(
            'id',
            sa.Integer(),
            nullable=False),
        sa.Column(
            'name',
            sa.String(
                length=100),
            nullable=False),
        sa.Column(
            'channel_link',
            sa.String(
                length=255),
            nullable=False),
        sa.Column(
            'is_deleted',
            sa.Boolean(),
            server_default='0',
            nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=True),
        sa.Column(
            'updated_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=True),
        sa.PrimaryKeyConstraint('id'))
    op.create_table('logs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('logger_name', sa.String(length=100), nullable=False),
                    sa.Column('level', sa.String(length=20), nullable=False),
                    sa.Column('message', sa.Text(), nullable=False),
                    sa.Column('data', sa.JSON(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table(
        'teams',
        sa.Column(
            'id',
            sa.Integer(),
            nullable=False),
        sa.Column(
            'name',
            sa.String(
                length=100),
            nullable=False),
        sa.Column(
            'city',
            sa.String(
                length=50),
            nullable=False),
        sa.Column(
            'is_deleted',
            sa.Boolean(),
            server_default='0',
            nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=True),
        sa.Column(
            'updated_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=True),
        sa.PrimaryKeyConstraint('id'))
    op.create_table('tournaments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('city', sa.String(length=50), nullable=False),
                    sa.Column('start_date', sa.DateTime(), nullable=False),
                    sa.Column('end_date', sa.DateTime(), nullable=False),
                    sa.Column('jtr_link', sa.String(length=255), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('videos',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('category', sa.Enum('REPORTS', 'HIGHLIGHTS', 'SPARBUILDING', 'MATCH', 'SONG', 'PODCAST', 'AWARDS', 'TRAINING', 'OTHER', name='videocategoriesenum'), nullable=False),
                    sa.Column('video_link', sa.String(length=255), nullable=False),
                    sa.Column('upload_date', sa.DateTime(), nullable=False),
                    sa.Column('comment', sa.Text(), nullable=False),
                    sa.Column('date_of_recording', sa.DateTime(), nullable=True),
                    sa.Column('game_system', sa.Enum('NRW', 'STONES', 'SETS', name='gamesystemtypesenum'), nullable=True),
                    sa.Column('weapon_type', sa.Enum('LONGSWORD', 'QTIP', 'CHAIN', 'SHIELD', 'STAFF', 'QWIK', name='weapontypesenum'), nullable=True),
                    sa.Column('topic', sa.String(length=100), nullable=False),
                    sa.Column('guests', sa.String(length=100), nullable=False),
                    sa.Column('channel_id', sa.Integer(), nullable=False),
                    sa.Column('tournament_id', sa.Integer(), nullable=True),
                    sa.Column('team_one_id', sa.Integer(), nullable=True),
                    sa.Column('team_two_id', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
                    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
                    sa.ForeignKeyConstraint(['team_one_id'], ['teams.id'], ),
                    sa.ForeignKeyConstraint(['team_two_id'], ['teams.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    op.drop_table('tournaments')
    op.drop_table('teams')
    op.drop_table('logs')
    op.drop_table('channels')
    # ### end Alembic commands ###
