"""add link-type column

Revision ID: e320c4edcc73
Revises: 16de9d54ae78
Create Date: 2025-05-09 11:01:22.457336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e320c4edcc73'
down_revision = '16de9d54ae78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_type', sa.Enum('YOUTUBE_CUSTOM', 'YOUTUBE_CHANNEL', 'OTHER', name='channellinktypesenum'), nullable=True))
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.create_unique_constraint(None, ['channel_link'])

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['jtr_link'])
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_type', sa.Enum('YOUTUBE', 'OTHER', name='videolinktypesenum'), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.create_unique_constraint(None, ['video_link'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('link_type')

    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('link_type')

    # ### end Alembic commands ###
